'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    ar: {
        // Sidebar & Navigation
        nav_home: 'الرئيسية',
        nav_scan: 'محطة المسح',
        nav_customers: 'العملاء',
        nav_cards: 'البطاقات',
        nav_discounts: 'الخصومات',
        nav_campaigns: 'إدارة الباقات',
        nav_transactions: 'سجل العمليات',
        nav_finance_hub: 'المركز المالي',
        nav_management: 'سجلات النظام',
        nav_terminals: 'مراقب الأجهزة',
        nav_logs: 'سجلات التدقيق',
        nav_users: 'إدارة المستخدمين',
        nav_settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        welcome: 'مرحباً',
        topup_btn: 'شحن رصيد / باقة',
        no_packages_title: 'لا توجد باقات',
        no_packages_desc: 'يرجى إنشاء باقات جديدة في مدير الباقات',
        days_label: 'يوم',
        discount: 'خصم',

        // Generic Actions
        add: 'إضافة',
        edit: 'تعديل',
        delete: 'حذف',
        save: 'حفظ',
        cancel: 'إلغاء',
        search: 'بحث...',
        loading: 'جاري التحميل...',
        no_data: 'لا توجد بيانات',
        actions: 'الإجراءات',
        status: 'الحالة',
        is_active: 'نشط',
        all_branches: 'كل الفروع',
        all: 'الكل',
        confirm: 'تأكيد',
        close: 'إغلاق',

        // Scan Page
        waiting_card: 'في انتظار البطاقة',
        scan_desc: 'ضع البطاقة على القارئ للبدء',
        processing: 'جاري المعالجة...',
        customer_not_found: 'العميل غير موجود',
        card_not_linked: 'البطاقة غير متصلة',
        total_savings: 'إجمالي التوفير',
        bill_amount: 'قيمة الفاتورة',
        pay_with_wallet: 'دفع من المحفظة',
        pay_cash: 'دفع نقدي',
        insufficient_balance: 'الرصيد غير كافٍ',
        active_packages: 'الباقات المتاحة',
        no_active_packages: 'لا توجد باقات جاهزة للاستخدام',
        credit_unit: 'باقة',
        confirm_payment: 'تأكيد الدفع',
        customer_wallet: 'رصيد المحفظة',
        remaining_cash: 'المتبقي (نقدي)',
        amount_to_pay_wallet: 'المبلغ للخصم من المحفظة',
        recharge_btn: 'شحن رصيد / شراء باقة',
        manual_topup: 'شحن رصيد نقدي',
        manual_topup_desc: 'إضافة رصيد مالي لمحفظة العميل',
        recharge_confirm_btn: 'إتمام الشحن',
        error_invalid_amount: 'يرجى إدخال مبلغ صحيح',
        scanning_effect: 'جاري المسح الضوئي...',
        saving_value: 'لقد وفرت {value} حتى الآن!',
        active_status: 'نشط',
        admin_controls: 'أدوات الإدارة',
        connection_error: 'خطأ في الاتصال',
        reset_confirm_title: 'تأكيد التصفير',
        build_status: 'حالة النظام',
        version_label: 'الإصدار',
        enter_amount_first: 'الرجاء إدخال مبلغ الفاتورة أولاً قبل اختيار الحصة',

        // Admin Tools
        admin_reset_balance: 'تصفير الرصيد',
        admin_clear_packages: 'تفريغ الباقات',
        confirm_reset_balance: 'هل أنت متأكد من تصفير الرصيد النقدي نهائياً؟',
        confirm_clear_packages: 'هل أنت متأكد من حذف كافة الباقات من البطاقة؟',
        reset_success: 'تم تنفيذ العملية بنجاح',
        reset_failed: 'فشلت العملية',
        network_error: 'خطأ في الاتصال',

        // Wallet
        topup_select_package: 'اختر الباقة المناسبة',
        empty_wallet: 'المحفظة فارغة',
        valid_until: 'صالح حتى',
        use_now: 'استخدم الآن',
        selected: 'تم الاختيار',
        confirm_use_btn: 'تأكيد الاستخدام',
        cancel_btn: 'إلغاء',
        coupon_used: 'تم استخدام الباقة بنجاح!',
        coupon_use_failed: 'فشل في استخدام الباقة',
        no_expiry: 'بدون تاريخ انتهاء',
        purchase_confirm: 'هل أنت متأكد من شراء {name} مقابل {price}؟',
        package_details: 'تفاصيل الباقة',
        price: 'السعر',
        usage_limit: 'عدد الوحدات',
        per_unit: 'لكل باقة',
        have_balance_msg: 'لديك رصيد متاح في المحفظة، يمكنك استخدامه لشراء باقات وعروض.',
        empty_wallet_desc: 'المحفظة فارغة تماماً، قم بشحن الرصيد للبدء في استخدام الخدمات.',

        // Settings Page
        settings_title: 'إعدادات النظام',
        settings_desc: 'تخصيص وإدارة تجربة النظام الخاصة بك',
        save_changes: 'حفظ التغييرات',
        tab_general: 'عام',
        tab_finance: 'المالية',
        tab_appearance: 'المظهر',
        tab_system: 'النظام',
        tab_developer: 'أدوات المطور',
        store_name: 'اسم المتجر',
        toast_duration: 'مدة التنبيهات (ms)',
        currency_symbol: 'رمز العملة',
        accent_color: 'اللون الأساسي',
        system_sounds: 'أصوات النظام',
        maintenance_mode: 'وضع الصيانة',
        maintenance_desc: 'إيقاف دخول غير الموظفين للنظام مؤقتاً',
        emergency_admin_restore: 'استعادة مدير النظام',
        emergency_admin_desc: 'إعادة إنشاء حساب المسؤول الافتراضي (admin/admin)',
        developer_notice: 'هذه الأدوات مخصصة للاستخدام التقني فقط. التلاعب بها قد يؤدي لتعطيل النظام.',
        upload_logo: 'رفع شعار',
        uploading: 'جاري الرفع...',
        logo_guide: 'دليل الشعار',
        logo_rec_square: 'يفضل استخدام شعار مربع أو دائري لتناسق القوائم.',
        logo_rec_wide: 'يفضل شفافية الخلفية (PNG).',
        logo_max_size: 'الحد الأقصى الموصى به: 2MB',
        system_info: 'حالة النظام',
        db_connection: 'اتصال البيانات',
        api_status: 'حالة الملقم',
        version: 'الإصدار',
        restart_system: 'إعادة تشغيل النظام',
        clear_cache: 'تفريغ الذاكرة المؤقتة',
        status_healthy: 'مستقر',
        status_active: 'نشط',
        on: 'مفعل',
        off: 'معطل',
        loading_settings: 'جاري تحميل الإعدادات...',
        save_success: 'تم حفظ التغييرات بنجاح',
        restore_success: 'تم استعادة المسؤول بنجاح',

        // Customers Page
        register_customer: 'تسجيل عميل جديد',
        show_deleted: 'الأرشيف',
        hide_deleted: 'الرجوع للقائمة',
        recycle_bin: 'سلة المحذوفات',
        customer_name: 'اسم العميل',
        card_uid: 'رقم البطاقة (UID)',
        customer_phone: 'رقم الهاتف',
        customer_email: 'البريد الإلكتروني',
        new_member_badge: 'عضوية جديدة',
        autofilled_msg: 'تم الملء تلقائياً من المسح',
        card_status_current: 'المتصل حالياً',
        card_status_recharge: 'شحن',
        card_status_available: 'متاح للاتصال',
        restore: 'استعادة',
        confirm_permanent_delete: 'هل أنت متأكد من حذف العميل نهائياً من قاعدة البيانات؟ لا يمكن التراجع عن هذا الإجراء.',
        promotion_badge: 'منطق العروض',
        customer_type_label: 'نوع العميل',
        type_single: 'أفراد (خصم 10%)',
        type_family: 'عائلات (خصم 20%)',
        type_single_short: 'أفراد',
        type_family_short: 'عائلات',
        customer_single: 'عضو فردي',
        customer_family: 'عضو عائلة',
        target_audience: 'الفئة المستهدفة',
        all_customers: 'جميع العملاء',

        // Campaigns Page
        campaigns_title: 'مدير الباقات',
        campaigns_desc: 'إنشاء وإدارة العروض الترويجية وباقات المشتريات',
        recycle_desc: 'الحملات التي تم حذفها مؤخراً',
        recycle_btn: 'العناصر المحذوفة',
        back_to_active: 'العودة للقائمة النشطة',
        new_campaign: 'إنشاء باقة جديدة',
        edit_campaign: 'تعديل الباقة',
        campaign_name: 'اسم الباقة / العرض',
        campaign_name_placeholder: 'مثال: باقة البريميوم، خصم الشتاء',
        campaign_description: 'وصف الباقة (اختياري)',
        campaign_description_placeholder: 'أضف تفاصيل إضافية عن الباقة...',
        validity_days: 'صلاحية الباقة (يوم)',
        reward_config: 'إعدادات الجائزة',
        reward_type: 'نوع الخصم',
        reward_percent: 'نسبة مئوية (%)',
        reward_fixed: 'مبلغ ثابت',
        reward_value: 'قيمة الخصم',
        launch_campaign: 'إطلاق الباقة',
        campaign_created_success: 'تم إنشاء الباقة بنجاح',
        type_auto_spend: 'تلقائي (حسب الإنفاق)',
        type_bundle: 'باقة مشتروات',
        type_manual: 'يدوي (إضافة مباشرة)',
        no_desc: 'لا يوجد وصف متاح لهذا العرض',
        trigger_rule_label: 'قاعدة التفعيل',
        rule_spend_above: 'عند إنفاق أكثر من',
        rule_collect_stamps: 'تجميع {count} طوابع / زيارات',
        rule_manual_only: 'يتم إضافته يدوياً للعملاء',
        reward_label: 'الجائزة المستحقة',
        off_label: 'خصم / باقة',
        delete_permanent: 'حذف نهائي',

        // Transactions & Logs
        status_success: 'مكتملة',
        status_failed: 'فاشلة',
        export_success: 'تم تصدير البيانات بنجاح',
        export: 'تصدير CSV',
        amount: 'المبلغ',
        date: 'التاريخ',
        customer_points: 'عدد الباقات',

        // Bundle Types
        bundle_type_family: 'باقات العائلة',
        bundle_type_meat_family: 'باقات اللحوم العائلية',
        bundle_type_youth: 'باقات الشباب',
        bundle_type_meat_individual: 'باقات اللحوم الفردية',
        bundle_type_individual: 'باقات الأفراد',
        bundle_type_default: 'باقات متنوعة',
        bundle_type: 'نوع الباقة',
        custom_splits: 'توزيع الحصص المخصص',

        // Cards Page
        link_card: 'توصيل بطاقة جديدة',
        expires_at: 'تاريخ الانتهاء',
        connected: 'متصل',
        disconnected: 'غير متصل',
        card_registry_badge: 'سجل البطاقات',
        default_expiry_msg: 'الافتراضي: 3 أشهر من الآن',

        // Audit Logs
        audit_error_load: 'فشل تحميل سجلات التدقيق',
        audit_clear_success: 'تم مسح السجلات بنجاح',
        audit_clear_error: 'فشل في مسح السجلات',
        audit_all: 'الكل',
        audit_auth: 'الأمان',
        audit_customers: 'العملاء',
        audit_cards: 'البطاقات',
        audit_campaigns: 'الحملات',
        audit_track_desc: 'مراقبة كافة التغييرات والعمليات الحساسة في النظام',
        audit_timestamp: 'الوقت',
        audit_admin: 'المسؤول',
        audit_action: 'العملية',
        audit_entity: 'الهدف',
        audit_details: 'التفاصيل',
        audit_no_logs: 'لا توجد سجلات مطابقة للبحث',
        audit_clear_confirm: 'تأكيد مسح السجلات',
        audit_clear_desc: 'سيتم مسح كافة سجلات التدقيق نهائياً. يرجى إدخال كلمة المرور للتأكيد.',
        action_create: 'إضافة',
        action_update: 'تعديل',
        action_delete: 'حذف',
        action_restore: 'استعادة',
        action_login: 'دخول',
        system: 'نظام آلي',

        // Management & Enterprise
        enterprise_management: 'إدارة المؤسسة',
        enterprise_desc: 'إدارة الفروع، الأجهزة، والمستخدمين من مكان واحد',
        tabs_branches: 'الفروع',
        tabs_terminals: 'الأجهزة',
        tabs_users: 'المستخدمين',
        add_branch: 'إضافة فرع',
        add_terminal: 'إضافة جهاز',
        add_user: 'إضافة مستخدم',
        branch_name: 'اسم الفرع',
        branch_location: 'الموقع',
        terminal_name: 'اسم الجهاز',
        terminal_branch: 'الفرع',
        terminal_secret: 'مفتاح الربط',
        username: 'اسم المستخدم',
        password: 'كلمة المرور',
        role: 'الصلاحية',
        admin: 'مدير',
        staff: 'موظف',
        superadmin: 'مدير نظام',
        password_hint: 'اتركه فارغاً للحفاظ على كلمة المرور الحالية',
        online: 'متصل',
        offline: 'غير متصل',
        deactivated: 'معطل',
        deleted: 'محذوف',
        active: 'نشط',
        total_terminals: 'إجمالي الأجهزة',
        currently_online: 'متصل حالياً',
        hardware_alerts: 'تنبيهات الهاردوير',
        terminal_script_status: 'حالة السكريبت',
        terminal_nfc_reader: 'قارئ NFC',
        terminal_last_seen: 'آخر تواجد',
        disconnected_status: 'غير متصل',

        // NFC Security
        tabs_nfc_security: 'أمن البطاقات',
        security_instructions: 'تعليمات الأمان',
        card_initialization: 'تهيئة البطاقات الجديدة',
        reader_disconnected: 'القارئ غير متصل',
        bridge_required_desc: 'يرجى تشغيل برنامج الجسر المحلي (NFC Bridge) وتوصيل القارئ لتفعيل هذه الميزة.',
        place_card_on_reader: 'ضع البطاقة على القارئ الآن...',
        card_detected: 'تم اكتشاف بطاقة',
        card_already_secured: 'بطاقة مؤمنة مسبقاً',
        card_unsecured: 'بطاقة غير مهيئة',
        card_unsupported: 'هذه البطاقة غير مدعومة',
        inject_signature_btn: 'بدء عملية الحقن الأمني',
        injecting_signature: 'جاري حقن التوقيع الأمني...',
        revoke_signature_btn: 'إلغاء التوقيع',
        revoking_signature: 'جاري إلغاء التوقيع...',
        revoke_signature_success: 'تم إلغاء التوقيع بنجاح',
        revoke_signature_failed: 'فشل إلغاء التوقيع',
        confirm_revoke_signature: 'هل أنت متأكد من إلغاء توقيع البطاقة؟',

        // Audit & Scan
        audit_clear: 'مسح السجلات',
        topup_modal_title: 'متجر الباقات',
        enterprise: 'المؤسسة',
        password: 'كلمة المرور',
        error_load: 'فشل تحميل البيانات',
        error_general: 'حدث خطأ ما',
        delete_success: 'تم الحذف بنجاح',
        delete_error: 'فشل الحذف',
        restore_error: 'فشل الاستعادة',
        confirm_delete: 'هل أنت متأكد من الحذف؟',
        topup_success: 'تمت عملية الشحن بنجاح',
        register_new_customer: 'تسجيل عميل جديد',
        valid_from: 'تاريخ البدء',
        days_remaining: 'يوم متبقي',
        card_expired: 'البطاقة منتهية',
        expiry_warning_days: 'أيام تنبيه انتهاء البطاقة',
        expiry_warning_desc: 'عدد الأيام قبل انتهاء البطاقة ليظهر تنبيه التحذير',
        enable_db_cleanup: 'تفعيل تنظيف قاعدة البيانات',
        db_cleanup_days: 'حذف السجلات الأقدم من (يوم)',
        db_cleanup_desc: 'سيتم حذف سجلات المسح المعالجة تلقائياً لتسريع النظام',
        manual_scan: 'مسح يدوي',
        enter_uid: 'أدخل رقم البطاقة',
        waiting_for_card_on_terminal: 'في انتظار وضع البطاقة على الماكينة...',
        select_terminal_first: 'يرجى اختيار الماكينة أولاً من صفحة المسح',
        card_scanned_success: 'تم قراءة البطاقة بنجاح',
        scan_timeout: 'انتهى وقت الانتظار',
        scanning: 'جاري المسح...',
        scan_from_terminal: 'مسح من الماكينة',
        scan: 'مسح',

        // Finance Hub
        finance_hub_title: 'المركز المالي',
        finance_hub_desc: 'تحليل التدفق النقدي، المبيعات، والخصومات الممنوحة',
        total_cash_revenue: 'إجمالي الدخل النقدي',
        total_wallet_spending: 'مشتريات المحفظة',
        total_topups: 'عمليات الشحن',
        total_savings: 'إجمالي الخصومات',
        revenue_vs_savings: 'الدخل مقابل الخصومات',
        spending_method_split: 'طرق الدفع المستخدمة',
        top_selling_packages: 'الباقات الأكثر مبيعاً',
        financial_growth: 'النمو المالي',
        wallet_retention: 'الأرصدة المعلقة',
        cash: 'نقداً',
        wallet: 'المحفظة',
        sales_count: 'مبيعات',
        generic_purchase: 'عمليات شراء عامة',
        security_note_title: 'ملاحظة أمنية',
        security_note_desc: 'كافة الأرقام المالية تعتمد على العمليات الناجحة فقط. العمليات الملغاة أو الفاشلة لا تحتسب ضمن هذه المؤشرات.',
        last_7_days: 'آخر 7 أيام',
        growth_performance_note_positive: 'الأداء أفضل بنسبة {percent}% من الأسبوع الماضي',
        growth_performance_note_negative: 'الأداء أقل بنسبة {percent}% من الأسبوع الماضي',

        // Security & Injection
        security_status: 'الحالة الأمنية',
        secured: 'مؤمنة (موقعة)',
        unsecured: 'غير مؤمنة',
        injection_success_title: 'تم الحقن بنجاح',
        injection_success_msg: 'تم حماية البطاقة وتوقيعها رقمياً بنجاح.',
        injection_failed_title: 'فشل الحقن',
        verify_before_add: 'يجب التحقق من أمان البطاقة قبل إضافتها',
        card_must_be_secured: 'عذراً، لا يمكن إضافة بطاقات غير موقعة للنظام.',
        secure_card_first: 'يرجى تأمين البطاقة أولاً من صفحة "أمن البطاقات"',
        card_verified_badge: 'بطاقة موثقة وآمنة',
        card_unverified_badge: 'بطاقة غير موثقة',
    },
    en: {
        // Sidebar & Navigation
        nav_home: 'Home',
        nav_scan: 'Scan Terminal',
        nav_customers: 'Customers',
        nav_cards: 'Cards',
        nav_discounts: 'Discounts',
        nav_campaigns: 'Package Manager',
        nav_transactions: 'Transactions',
        nav_finance_hub: 'Financial Hub',
        nav_management: 'Management',
        nav_terminals: 'Terminal Monitor',
        nav_logs: 'Audit Logs',
        nav_users: 'User Management',
        nav_settings: 'Settings',
        logout: 'Logout',
        welcome: 'Welcome',
        topup_btn: 'Top-up / Package',
        no_packages_title: 'No Packages',
        no_packages_desc: 'Please create new packages in Package Manager',
        days_label: 'Days',
        discount: 'Discount',

        // Generic Actions
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        search: 'Search...',
        loading: 'Loading...',
        no_data: 'No data available',
        actions: 'Actions',
        status: 'Status',
        is_active: 'Active',
        all_branches: 'All Branches',
        all: 'All',
        confirm: 'Confirm',
        close: 'Close',

        // Scan Page
        waiting_card: 'Waiting for Card',
        scan_desc: 'Place NFC card on reader to start',
        processing: 'Processing...',
        customer_not_found: 'Customer not found',
        card_not_linked: 'Card not linked',
        total_savings: 'Total Savings',
        bill_amount: 'Bill Amount',
        pay_with_wallet: 'Pay from Wallet',
        pay_cash: 'Cash Payment',
        insufficient_balance: 'Insufficient Balance',
        active_packages: 'Purchased Packages',
        no_active_packages: 'No active packages ready',
        credit_unit: 'Package',
        confirm_payment: 'Confirm Payment',
        customer_wallet: 'Wallet Balance',
        recharge_btn: 'Top-up / Buy Package',
        manual_topup: 'Cash Top-up',
        manual_topup_desc: 'Add cash balance to customer wallet',
        recharge_confirm_btn: 'Complete Recharge',
        error_invalid_amount: 'Please enter a valid amount',
        scanning_effect: 'Scanning...',
        saving_value: 'You saved {value} so far!',
        active_status: 'Active',
        admin_controls: 'Administrative Controls',
        connection_error: 'Connection Error',
        reset_confirm_title: 'Confirm Reset',
        build_status: 'Build Status',
        version_label: 'VERSION',
        enter_amount_first: 'Please enter the bill amount first before selecting a quota',

        // Admin Tools
        admin_reset_balance: 'Reset Balance',
        admin_clear_packages: 'Clear Packages',
        confirm_reset_balance: 'Are you sure you want to permanently reset the cash balance?',
        confirm_clear_packages: 'Are you sure you want to remove all packages from the card?',
        reset_success: 'Operation completed successfully',
        reset_failed: 'Operation failed',
        network_error: 'Network Error',

        // Wallet
        topup_select_package: 'Select a Package',
        empty_wallet: 'Empty Wallet',
        valid_until: 'Valid until',
        use_now: 'Use Now',
        selected: 'Selected',
        confirm_use_btn: 'Confirm Use',
        cancel_btn: 'Cancel',
        coupon_used: 'Package used successfully!',
        coupon_use_failed: 'Failed to use package',
        no_expiry: 'No expiry date',
        purchase_confirm: 'Are you sure you want to buy {name} for {price}?',
        package_details: 'Package Details',
        price: 'Price',
        usage_limit: 'Units count',
        per_unit: 'Per Package',
        have_balance_msg: 'You have available balance in your wallet.',
        empty_wallet_desc: 'Wallet is completely empty. Recharge to start.',

        // Settings Page
        settings_title: 'System Settings',
        settings_desc: 'Customize and manage your system experience',
        save_changes: 'Save Changes',
        tab_general: 'General',
        tab_finance: 'Finance',
        tab_appearance: 'Appearance',
        tab_system: 'System',
        tab_developer: 'Developer Tools',
        store_name: 'Store Name',
        toast_duration: 'Toast Duration (ms)',
        currency_symbol: 'Currency Symbol',
        accent_color: 'Accent Color',
        system_sounds: 'System Sounds',
        maintenance_mode: 'Maintenance Mode',
        maintenance_desc: 'Temporarily disable non-staff access',
        emergency_admin_restore: 'Emergency Admin Restore',
        emergency_admin_desc: 'Restore default admin account (admin/admin)',
        developer_notice: 'These tools are for technical use only. Misuse may damage system integrity.',
        upload_logo: 'Upload Logo',
        uploading: 'Uploading...',
        logo_guide: 'Logo Guide',
        logo_rec_square: 'Square or round logos work best for icons.',
        logo_rec_wide: 'Transparent background (PNG) is recommended.',
        logo_max_size: 'Maximum recommended size: 2MB',
        system_info: 'System Information',
        db_connection: 'DB Connection',
        api_status: 'API Status',
        version: 'Version',
        restart_system: 'Restart Instance',
        clear_cache: 'Clear System Cache',
        status_healthy: 'Healthy',
        status_active: 'Active',
        on: 'ON',
        off: 'OFF',
        loading_settings: 'Loading Settings...',
        save_success: 'Settings saved successfully',
        restore_success: 'Admin restored successfully',

        // Customers Page
        register_customer: 'Register Customer',
        show_deleted: 'Show Deleted',
        hide_deleted: 'Hide Deleted',
        recycle_bin: 'Recycle Bin',
        customer_name: 'Customer Name',
        card_uid: 'Card UID',
        customer_phone: 'Phone Number',
        customer_email: 'Email Address',
        new_member_badge: 'New Member',
        autofilled_msg: 'Auto-filled from scan',
        card_status_current: 'Current',
        card_status_recharge: 'Recharge',
        card_status_available: 'Available',
        restore: 'Restore',
        confirm_permanent_delete: 'Are you sure you want to delete this customer permanently? This action cannot be undone.',
        promotion_badge: 'Promotion Logic',
        customer_type_label: 'Customer Type',
        type_single: 'Individuals (10% Off)',
        type_family: 'Families (20% Off)',
        type_single_short: 'Individuals',
        type_family_short: 'Families',
        customer_single: 'Single Member',
        customer_family: 'Family Member',
        target_audience: 'Target Audience',
        all_customers: 'All Customers',

        // Campaigns Page
        campaigns_title: 'Package Manager',
        campaigns_desc: 'Create and manage promotions and purchase bundles',
        recycle_desc: 'Recently deleted campaigns and packages',
        recycle_btn: 'Recycle Bin',
        back_to_active: 'Back to Active',
        new_campaign: 'New Package',
        edit_campaign: 'Edit Package',
        campaign_name: 'Package/Campaign Name',
        campaign_name_placeholder: 'e.g., Premium Bundle, Winter Discount',
        campaign_description: 'Package Description (Optional)',
        campaign_description_placeholder: 'Add extra details about the package...',
        validity_days: 'Package Validity (Days)',
        reward_config: 'Reward Configuration',
        reward_type: 'Discount Type',
        reward_percent: 'Percentage (%)',
        reward_fixed: 'Fixed Amount',
        reward_value: 'Discount Value',
        launch_campaign: 'Launch Package',
        campaign_created_success: 'Package created successfully',
        type_auto_spend: 'Auto (Spend Base)',
        type_bundle: 'Bundle Package',
        type_manual: 'Manual Addition',
        no_desc: 'No description available for this offer',
        trigger_rule_label: 'Trigger Rule',
        rule_spend_above: 'Spend above',
        rule_collect_stamps: 'Collect {count} stamps/visits',
        rule_manual_only: 'Manually assigned to customers',
        reward_label: 'Earned Reward',
        off_label: 'OFF',
        delete_permanent: 'Delete Permanently',

        // Transactions & Logs
        status_success: 'SUCCESS',
        status_failed: 'FAILED',
        export_success: 'Data exported successfully',
        export: 'Export CSV',
        amount: 'Amount',
        date: 'Date',
        customer_points: 'Package Count',

        // Bundle Types
        bundle_type_family: 'Family Bundles',
        bundle_type_meat_family: 'Meat Family Bundles',
        bundle_type_youth: 'Youth Bundles',
        bundle_type_meat_individual: 'Meat Individual Bundles',
        bundle_type_individual: 'Individual Bundles',
        bundle_type_default: 'Other Bundles',
        bundle_type: 'Bundle Type',
        custom_splits: 'Custom Splits',

        // Cards Page
        link_card: 'Link New Card',
        expires_at: 'Expires At',
        connected: 'Connected',
        disconnected: 'Disconnected',
        card_registry_badge: 'NFC Registry',
        default_expiry_msg: 'Default: 3 months from now',

        // Audit Logs
        audit_error_load: 'Failed to load audit logs',
        audit_clear_success: 'Logs cleared successfully',
        audit_clear_error: 'Failed to clear logs',
        audit_all: 'All',
        audit_auth: 'Security',
        audit_customers: 'Customers',
        audit_cards: 'Cards',
        audit_campaigns: 'Campaigns',
        audit_track_desc: 'Monitor all changes and sensitive operations in the system',
        audit_timestamp: 'Timestamp',
        audit_admin: 'Admin',
        audit_action: 'Action',
        audit_entity: 'Entity',
        audit_details: 'Details',
        audit_no_logs: 'No audit logs found',
        audit_clear_confirm: 'Confirm Clear Logs',
        audit_clear_desc: 'All audit logs will be permanently deleted. Enter password to confirm.',
        action_create: 'CREATE',
        action_update: 'UPDATE',
        action_delete: 'DELETE',
        action_restore: 'RESTORE',
        action_login: 'LOGIN',
        system: 'System Auto',

        // Management & Enterprise
        enterprise_management: 'Enterprise Management',
        enterprise_desc: 'Manage branches, terminals, and users from one place',
        tabs_branches: 'Branches',
        tabs_terminals: 'Terminals',
        tabs_users: 'Users',
        add_branch: 'Add Branch',
        add_terminal: 'Add Terminal',
        add_user: 'Add User',
        branch_name: 'Branch Name',
        branch_location: 'Location',
        terminal_name: 'Terminal Name',
        terminal_branch: 'Branch',
        terminal_secret: 'Terminal Secret',
        username: 'Username',
        password: 'Password',
        role: 'Role',
        admin: 'Admin',
        staff: 'Staff',
        superadmin: 'Super Admin',
        password_hint: 'Leave empty to keep current password',
        online: 'Online',
        offline: 'Offline',
        deactivated: 'Deactivated',
        deleted: 'Deleted',
        active: 'Active',
        total_terminals: 'Total Terminals',
        currently_online: 'Currently Online',
        hardware_alerts: 'Hardware Alerts',
        terminal_script_status: 'Script Status',
        terminal_nfc_reader: 'NFC Reader',
        terminal_last_seen: 'Last Seen',
        disconnected_status: 'Disconnected',

        // NFC Security
        tabs_nfc_security: 'Card Security',
        security_instructions: 'Security Instructions',
        card_initialization: 'Card Initialization',
        reader_disconnected: 'Reader Disconnected',
        bridge_required_desc: 'Please run the local NFC Bridge and connect a reader to enable this feature.',
        place_card_on_reader: 'Place card on reader...',
        card_detected: 'Card Detected',
        card_already_secured: 'Card Already Secured',
        card_unsecured: 'Unsecured Card',
        card_unsupported: 'This card is not supported',
        inject_signature_btn: 'Inject Security Signature',
        injecting_signature: 'Injecting Signature...',
        revoke_signature_btn: 'Revoke Signature',
        revoking_signature: 'Revoking Signature...',
        revoke_signature_success: 'Signature revoked successfully',
        revoke_signature_failed: 'Failed to revoke signature',
        confirm_revoke_signature: 'Are you sure you want to revoke this card\'s signature?',

        // Audit & Scan
        audit_clear: 'Clear Logs',
        topup_modal_title: 'Package Store',
        enterprise: 'Enterprise',
        password: 'Password',
        error_load: 'Failed to load data',
        error_general: 'Something went wrong',
        delete_success: 'Deleted successfully',
        delete_error: 'Delete failed',
        restore_error: 'Restore failed',
        confirm_delete: 'Are you sure you want to delete?',
        topup_success: 'Top-up successful',
        register_new_customer: 'Register New Customer',
        valid_from: 'Valid From',
        days_remaining: 'Days Remaining',
        card_expired: 'Card Expired',
        expiry_warning_days: 'Expiry Warning Days',
        expiry_warning_desc: 'Days before expiry to show warning alert',
        enable_db_cleanup: 'Enable DB Cleanup',
        db_cleanup_days: 'Delete logs older than (days)',
        db_cleanup_desc: 'Processed scan logs will be auto-deleted to optimize performance',
        manual_scan: 'Manual Scan',
        enter_uid: 'Enter Card UID',
        waiting_for_card_on_terminal: 'Waiting for card on terminal...',
        select_terminal_first: 'Please select a terminal first from the Scan page',
        card_scanned_success: 'Card scanned successfully',
        scan_timeout: 'Scan timed out',
        scanning: 'Scanning...',
        scan_from_terminal: 'Scan from Terminal',
        scan: 'Scan',

        // Finance Hub
        finance_hub_title: 'Financial Hub',
        finance_hub_desc: 'Analyze cash flow, sales performance, and discounts',
        total_cash_revenue: 'Cash Revenue',
        total_wallet_spending: 'Wallet Spending',
        total_topups: 'Total Top-ups',
        total_savings: 'Total Savings',
        revenue_vs_savings: 'Revenue vs Savings',
        spending_method_split: 'Payment Methods Split',
        top_selling_packages: 'Best Selling Packages',
        financial_growth: 'Financial Growth',
        wallet_retention: 'Wallet Retention',
        cash: 'Cash',
        wallet: 'Wallet',
        sales_count: 'Sales',
        generic_purchase: 'Generic Purchase',
        security_note_title: 'Security Note',
        security_note_desc: 'All financial figures are based on successful transactions only. Voided or failed attempts are not included in these metrics.',
        last_7_days: 'Last 7 Days',
        growth_performance_note_positive: 'Performance is {percent}% better than last week',
        growth_performance_note_negative: 'Performance is {percent}% lower than last week',

        // Security & Injection
        security_status: 'Security Status',
        secured: 'Secured (Signed)',
        unsecured: 'Unsecured',
        injection_success_title: 'Injection Successful',
        injection_success_msg: 'Card protected and digitally signed successfully.',
        injection_failed_title: 'Injection Failed',
        verify_before_add: 'Security verification required before adding',
        card_must_be_secured: 'Unsigned cards cannot be added to the system.',
        secure_card_first: 'Please secure the card first from "Card Security" page',
        card_verified_badge: 'Verified & Secure Card',
        card_unverified_badge: 'Unverified Card',
    }
};

export function LanguageProvider({ children }) {
    // 🛡️ Fix Hydration Mismatch: Always start with 'ar' (server-side default)
    const [language, setLanguage] = useState('ar');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        // Now we are on the client
        const savedLang = localStorage.getItem('app_lang') || 'ar';
        setLanguage(savedLang);
        setMounted(true);

        document.dir = savedLang === 'ar' ? 'rtl' : 'ltr';
        document.lang = savedLang;
    }, []);

    useEffect(() => {
        if (mounted) {
            localStorage.setItem('app_lang', language);
            document.dir = language === 'ar' ? 'rtl' : 'ltr';
            document.lang = language;
        }
    }, [language, mounted]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
    };

    // 🛡️ Fix Hydration: DO NOT return null. Render children with a default state ('ar') 
    // and update once mounted to preserve server-side HTML.
    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
