'use client';
import { useState, useEffect } from 'react';
import { useLanguage } from '@/lib/LanguageContext';
import { format } from 'date-fns';
import { Loader2, Database, Download, Clock, HardDrive } from 'lucide-react';
import { toast } from 'sonner';

export default function BackupsPage() {
    const { language } = useLanguage();
    const [backups, setBackups] = useState([]);
    const [loading, setLoading] = useState(true);
    const [creating, setCreating] = useState(false);
    const [exportingLocal, setExportingLocal] = useState(false);
    const [restoreFile, setRestoreFile] = useState(null);
    const [restoring, setRestoring] = useState(false);
    const [dryRunRestore, setDryRunRestore] = useState(true);
    const [restoreSummary, setRestoreSummary] = useState(null);

    // Schedule State (Mock persistence)
    const [schedule, setSchedule] = useState('DAILY'); // OFF, DAILY, WEEKLY

    useEffect(() => {
        fetchBackups();
    }, []);

    const fetchBackups = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/backups');
            const data = await res.json();
            const files = Array.isArray(data)
                ? data
                : (Array.isArray(data?.files) ? data.files : []);
            setBackups(files);
        } catch (error) {
            toast.error('Failed to load backups');
        } finally {
            setLoading(false);
        }
    };

    const handleCreateBackup = async () => {
        setCreating(true);
        try {
            const res = await fetch('/api/backups', { method: 'POST' });
            const data = await res.json();
            if (res.ok) {
                toast.success(language === 'ar' ? 'تم إنشاء النسخة الاحتياطية' : 'Backup created successfully');
                fetchBackups();
            } else {
                throw new Error(data.error);
            }
        } catch (error) {
            toast.error(error.message || 'Backup failed');
        } finally {
            setCreating(false);
        }
    };

    const handleDownload = async (fileName) => {
        try {
            // Request Signed URL from API (Securely generated by Admin)
            const res = await fetch(`/api/backups?action=download&file=${fileName}`);
            const data = await res.json();

            if (!res.ok) throw new Error(data.error);

            // Trigger download
            window.open(data.signedUrl, '_blank');
        } catch (error) {
            toast.error('Failed to generate download link');
        }
    };

    const handleExportLocal = async () => {
        setExportingLocal(true);
        try {
            const res = await fetch('/api/backups?action=export');
            if (!res.ok) {
                const err = await res.json().catch(() => ({}));
                throw new Error(err.error || 'Failed to export backup');
            }

            const blob = await res.blob();
            const disposition = res.headers.get('content-disposition') || '';
            const nameMatch = disposition.match(/filename="([^"]+)"/i);
            const fileName = nameMatch?.[1] || `backup_local_${Date.now()}.json`;

            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = fileName;
            document.body.appendChild(a);
            a.click();
            a.remove();
            URL.revokeObjectURL(url);

            toast.success(language === 'ar' ? 'تم تنزيل نسخة محلية' : 'Local backup downloaded');
        } catch (error) {
            toast.error(error.message || 'Export failed');
        } finally {
            setExportingLocal(false);
        }
    };

    const handleRestore = async () => {
        if (!restoreFile) {
            toast.error(language === 'ar' ? 'اختر ملف نسخة JSON أولاً' : 'Choose a JSON backup file first');
            return;
        }

        setRestoring(true);
        setRestoreSummary(null);
        try {
            const text = await restoreFile.text();
            const json = JSON.parse(text);

            const res = await fetch('/api/backups', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'restore',
                    backup: json,
                    dry_run: dryRunRestore,
                    chunk_size: 500,
                }),
            });

            const data = await res.json();
            if (!res.ok && res.status !== 207) {
                throw new Error(data.error || data.message || 'Restore failed');
            }

            if (data?.summary) {
                setRestoreSummary(data.summary);
            }

            if (res.status === 207 || data?.success === false) {
                toast.warning(language === 'ar' ? 'اكتمل الاسترجاع مع بعض الأخطاء' : 'Restore finished with some errors');
            } else {
                toast.success(
                    dryRunRestore
                        ? (language === 'ar' ? 'نجح الفحص بدون تطبيق (Dry Run)' : 'Dry run completed successfully')
                        : (language === 'ar' ? 'تم الاسترجاع بنجاح' : 'Restore completed successfully')
                );
            }

            fetchBackups();
        } catch (error) {
            toast.error(error.message || 'Restore failed');
        } finally {
            setRestoring(false);
        }
    };

    return (
        <div className="p-6 max-w-7xl mx-auto space-y-8" dir={language === 'ar' ? 'rtl' : 'ltr'}>

            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-gray-800 p-8 rounded-[2.5rem] shadow-sm border border-gray-100 dark:border-gray-700">
                <div>
                    <h1 className="text-3xl font-black text-gray-900 dark:text-white flex items-center gap-3">
                        <Database className="text-purple-600" size={32} />
                        {language === 'ar' ? 'النسخ الاحتياطي' : 'System Backups'}
                    </h1>
                    <p className="text-gray-500 mt-2 font-medium">
                        {language === 'ar' ? 'إدارة النسخ الاحتياطية لقاعدة البيانات والملفات' : 'Manage database and file backups'}
                    </p>
                </div>

                <button
                    onClick={handleCreateBackup}
                    disabled={creating}
                    className="flex items-center gap-2 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-xl shadow-purple-200 dark:shadow-none hover:scale-105 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {creating ? <Loader2 className="animate-spin" /> : <HardDrive size={20} />}
                    {language === 'ar' ? (creating ? 'جاري النسخ...' : 'نسخة يدوية الآن') : (creating ? 'Backing up...' : 'Manual Backup')}
                </button>

                <button
                    onClick={handleExportLocal}
                    disabled={exportingLocal}
                    className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-8 py-4 rounded-2xl font-bold transition-all shadow-xl shadow-emerald-200 dark:shadow-none hover:scale-105 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {exportingLocal ? <Loader2 className="animate-spin" /> : <Download size={20} />}
                    {language === 'ar' ? (exportingLocal ? 'جاري التنزيل...' : 'نسخة محلية JSON') : (exportingLocal ? 'Downloading...' : 'Local JSON Backup')}
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

                {/* Schedule Config */}
                <div className="lg:col-span-1 bg-white dark:bg-gray-800 p-6 rounded-[2rem] shadow-xl border border-gray-100 dark:border-gray-700 h-fit">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-6 flex items-center gap-2">
                        <Clock className="text-orange-500" />
                        {language === 'ar' ? 'النسخ المجدول' : 'Scheduled Backup'}
                    </h3>

                    <div className="space-y-4">
                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all border-blue-500 bg-blue-50 dark:bg-blue-900/20">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'DAILY'}
                                    onChange={() => setSchedule('DAILY')}
                                    className="w-5 h-5 text-blue-600"
                                />
                                <span className="font-bold text-blue-900 dark:text-blue-100">
                                    {language === 'ar' ? 'يومياً (منتصف الليل)' : 'Daily (Midnight)'}
                                </span>
                            </label>
                        </div>

                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-gray-700 border-gray-200 dark:border-gray-600">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'WEEKLY'}
                                    onChange={() => setSchedule('WEEKLY')}
                                    className="w-5 h-5 text-gray-600"
                                />
                                <span className="font-bold text-gray-700 dark:text-gray-300">
                                    {language === 'ar' ? 'أسبوعياً' : 'Weekly'}
                                </span>
                            </label>
                        </div>

                        <div className="p-4 rounded-xl border-2 cursor-pointer transition-all hover:bg-gray-50 dark:hover:bg-gray-700 border-gray-200 dark:border-gray-600">
                            <label className="flex items-center gap-3 cursor-pointer">
                                <input
                                    type="radio"
                                    name="schedule"
                                    checked={schedule === 'OFF'}
                                    onChange={() => setSchedule('OFF')}
                                    className="w-5 h-5 text-gray-600"
                                />
                                <span className="font-bold text-gray-700 dark:text-gray-300">
                                    {language === 'ar' ? 'إيقاف' : 'Disabled'}
                                </span>
                            </label>
                        </div>
                    </div>

                    <button className="w-full mt-6 bg-gray-900 dark:bg-gray-700 text-white py-3 rounded-xl font-bold hover:bg-black transition-colors">
                        {language === 'ar' ? 'حفظ الإعدادات' : 'Save Settings'}
                    </button>

                    <p className="text-xs text-center text-gray-400 mt-4">
                        {language === 'ar' ? 'ملاحظة: يتطلب هذا إعداد Cron Job على السيرفر.' : 'Note: This requires Cron Job setup on server.'}
                    </p>

                    <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700 space-y-3">
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white">
                            {language === 'ar' ? 'استرجاع نسخة JSON' : 'Restore JSON Backup'}
                        </h4>

                        <input
                            type="file"
                            accept="application/json,.json"
                            onChange={(e) => {
                                setRestoreFile(e.target.files?.[0] || null);
                                setRestoreSummary(null);
                            }}
                            className="w-full text-sm text-gray-700 dark:text-gray-300 file:me-3 file:px-3 file:py-2 file:rounded-lg file:border-0 file:bg-gray-100 dark:file:bg-gray-700 file:text-gray-700 dark:file:text-gray-200"
                        />

                        <label className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-300">
                            <input
                                type="checkbox"
                                checked={dryRunRestore}
                                onChange={(e) => setDryRunRestore(e.target.checked)}
                            />
                            {language === 'ar' ? 'فحص فقط (Dry Run بدون كتابة)' : 'Dry run only (no write)'}
                        </label>

                        <button
                            onClick={handleRestore}
                            disabled={restoring || !restoreFile}
                            className="w-full mt-1 bg-amber-600 hover:bg-amber-700 text-white py-3 rounded-xl font-bold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {restoring
                                ? (language === 'ar' ? 'جاري الاسترجاع...' : 'Restoring...')
                                : (dryRunRestore
                                    ? (language === 'ar' ? 'فحص النسخة' : 'Validate Backup')
                                    : (language === 'ar' ? 'استرجاع الآن' : 'Restore Now'))}
                        </button>

                        {restoreSummary && (
                            <div className="mt-4 rounded-xl border border-slate-200 dark:border-slate-700 p-3 bg-slate-50 dark:bg-slate-900/40 space-y-3">
                                <div className="flex items-center justify-between text-sm">
                                    <span className="font-bold text-slate-700 dark:text-slate-200">
                                        {language === 'ar' ? 'تقرير الاسترجاع' : 'Restore Report'}
                                    </span>
                                    <span className={`text-xs font-black px-2 py-1 rounded ${restoreSummary.failed_tables?.length ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'}`}>
                                        {restoreSummary.failed_tables?.length
                                            ? (language === 'ar' ? 'مع أخطاء' : 'With Errors')
                                            : (language === 'ar' ? 'ناجح' : 'Success')}
                                    </span>
                                </div>

                                <div className="grid grid-cols-2 gap-2 text-xs">
                                    <div className="p-2 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                                        <div className="text-slate-500">{language === 'ar' ? 'الإجمالي' : 'Total Rows'}</div>
                                        <div className="font-black text-slate-800 dark:text-slate-100">{restoreSummary.total_rows ?? 0}</div>
                                    </div>
                                    <div className="p-2 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                                        <div className="text-slate-500">{language === 'ar' ? 'فحص فقط' : 'Dry Run'}</div>
                                        <div className="font-black text-slate-800 dark:text-slate-100">{restoreSummary.dry_run ? 'Yes' : 'No'}</div>
                                    </div>
                                </div>

                                <div className="max-h-40 overflow-auto space-y-1 text-xs">
                                    {Object.entries(restoreSummary.tables || {}).map(([tableName, info]) => (
                                        <div key={tableName} className="flex items-center justify-between p-2 rounded bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
                                            <span className="font-mono text-slate-700 dark:text-slate-300">{tableName}</span>
                                            <span className="font-bold text-slate-900 dark:text-slate-100">{info?.restored ?? 0}/{info?.rows ?? 0}</span>
                                        </div>
                                    ))}
                                </div>

                                {(restoreSummary.failed_tables || []).length > 0 && (
                                    <div className="space-y-1 text-xs">
                                        <div className="font-bold text-red-600 dark:text-red-300">{language === 'ar' ? 'الجداول التي فشلت:' : 'Failed Tables:'}</div>
                                        {(restoreSummary.failed_tables || []).map((f, idx) => (
                                            <div key={`${f.table}-${idx}`} className="p-2 rounded bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700/40 text-red-700 dark:text-red-300">
                                                <div className="font-mono">{f.table}</div>
                                                <div className="opacity-90">{f.message}</div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                </div>

                {/* Backups List */}
                <div className="lg:col-span-2 bg-white dark:bg-gray-800 rounded-[2rem] shadow-xl border border-gray-100 dark:border-gray-700 overflow-hidden">
                    <div className="p-6 border-b border-gray-100 dark:border-gray-700">
                        <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                            {language === 'ar' ? 'سجل النسخ الاحتياطية' : 'Backup History'}
                        </h3>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-gray-50 dark:bg-gray-900/50">
                                <tr>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'اسم الملف' : 'Filename'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'التاريخ' : 'Date'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'الحجم' : 'Size'}
                                    </th>
                                    <th className="px-6 py-4 text-start text-xs font-black text-gray-400 uppercase tracking-wider">
                                        {language === 'ar' ? 'تحميل' : 'Download'}
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
                                {loading ? (
                                    <tr>
                                        <td colSpan="4" className="px-6 py-12 text-center">
                                            <Loader2 className="animate-spin mx-auto text-purple-500" size={32} />
                                        </td>
                                    </tr>
                                ) : backups.length === 0 ? (
                                    <tr>
                                        <td colSpan="4" className="px-6 py-12 text-center text-gray-400">
                                            {language === 'ar' ? 'لم يتم العثور على نسخ احتياطية' : 'No backups found'}
                                        </td>
                                    </tr>
                                ) : (
                                    backups.map((file) => (
                                        <tr key={file.id} className="hover:bg-gray-50/50 dark:hover:bg-gray-800/50 transition-colors">
                                            <td className="px-6 py-4 text-sm font-bold text-gray-700 dark:text-gray-300 font-mono">
                                                {file.name}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500">
                                                {format(new Date(file.created_at), 'yyyy/MM/dd HH:mm')}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-500">
                                                {(file.metadata?.size / 1024).toFixed(2)} KB
                                            </td>
                                            <td className="px-6 py-4">
                                                <button
                                                    onClick={() => handleDownload(file.name)}
                                                    className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                                    title="Download"
                                                >
                                                    <Download size={20} />
                                                </button>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
}
